config/routes.rb
Rails.application.routes.draw do

  get 'progress_bars/show'

  resources :companies
  root :to => 'static#home'

resources :progress_bars

resources :products do
  collection do 
    get :search, :action => 'search_post', :as => 'search_post'
    get 'search/:query', :action => 'search', :as => 'search'
    get 'search/:query/:page', :action => 'search', :as => 'search_page'
  end
end

  resources :searchterms do
    collection do
      get :warm, :action =>'warm', :as => 'warm'
    end
  end

require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'

end

app/models/searchterm.rb
class Searchterm < ActiveRecord::Base
end

app/controllers/searchterms_controller.rb
class SearchtermsController < ApplicationController

  include SearchtermsHelper
  include ProductsHelper

  before_action :set_searchterm, only: [:show, :edit, :update, :destroy]

  # GET /searchterms
  # GET /searchterms.json
  def index
    @searchterms = Searchterm.all
  end

  # GET /searchterms/1
  # GET /searchterms/1.json
  def show
  end

  # GET /searchterms/1
  # GET /searchterms/1.json
  def warm
    @searchterms = Searchterm.uniq.pluck(:query)
    @pb = ProgressBar.create(message: 'Queued',percent:0)
    warmthecache(@searchterms,@pb)
    #foreach of the @searchterms
    #Products.get_products(searchterm)
  end

  # GET /searchterms/new
  def new
    @searchterm = Searchterm.new
  end

  # GET /searchterms/1/edit
  def edit
  end

  # POST /searchterms
  # POST /searchterms.json
  def create
    @searchterm = Searchterm.new(searchterm_params)
    @sq = @searchterm.query
    GetProducts(@sq)
    respond_to do |format|
      if @searchterm.save
        format.html { redirect_to @searchterm, notice: 'Searchterm was successfully created.' }
        format.json { render :show, status: :created, location: @searchterm }
      else
        format.html { render :new }
        format.json { render json: @searchterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searchterms/1
  # PATCH/PUT /searchterms/1.json
  def update
    respond_to do |format|
      if @searchterm.update(searchterm_params)
        format.html { redirect_to @searchterm, notice: 'Searchterm was successfully updated.' }
        format.json { render :show, status: :ok, location: @searchterm }
      else
        format.html { render :edit }
        format.json { render json: @searchterm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searchterms/1
  # DELETE /searchterms/1.json
  def destroy
    @searchterm.destroy
    respond_to do |format|
      format.html { redirect_to searchterms_url, notice: 'Searchterm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_searchterm
    @searchterm = Searchterm.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def searchterm_params
    params.require(:searchterm).permit(:query)
  end
end

app/helpers/searchterms_helper.rb
include ProductsHelper
module SearchtermsHelper
	def warmthecache(terms,pb)
		WarmCacheJob.perform_later(terms,pb)
	end
end

app/views/searchterms/_form.html.erb
<%= form_for @searchterm, :html => { :class => "form-horizontal searchterm" } do |f| %>

  <% if @searchterm.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@searchterm.errors.count, "error") %> prohibited this searchterm from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @searchterm.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :query, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :query, :class => 'form-control' %>
    </div>
    <%=f.error_span(:query) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                searchterms_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/searchterms/edit.html.erb
<%- model_class = Searchterm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/searchterms/index.html.erb
<%- model_class = Searchterm -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:query) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @searchterms.each do |searchterm| %>
      <tr>
        <td><%= link_to searchterm.id, searchterm_path(searchterm) %></td>
        <td><%= searchterm.query %></td>
        <td><%=l searchterm.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_searchterm_path(searchterm), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      searchterm_path(searchterm),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_searchterm_path,
            :class => 'btn btn-primary' %>

app/views/searchterms/new.html.erb
<%- model_class = Searchterm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/searchterms/show.html.erb
<%- model_class = Searchterm -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:query) %>:</strong></dt>
  <dd><%= @searchterm.query %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              searchterms_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_searchterm_path(@searchterm), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              searchterm_path(@searchterm),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/searchterms/warm.html.erb
<div id="demo" data-ping-time="1000">
  <div class="progress">
     <div class="progress-bar progress-bar-info progress-bar-striped .active" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width:0%"><span class="sr-only">20% Complete</span></div>
  </div>
   <div class="message">Not Running...</div>
</div>
<script>
progressBar = new ProgressBar("#demo", "<%= progress_bar_path @pb.id %>")
progressBar.start()
</script>