config/routes.rb
Rails.application.routes.draw do

  get 'progress_bars/show'

  resources :companies
  root :to => 'static#home'

resources :progress_bars

resources :products do
  collection do 
    get :search, :action => 'search_post', :as => 'search_post'
    get 'search/:query', :action => 'search', :as => 'search'
    get 'search/:query/:page', :action => 'search', :as => 'search_page'
  end
end

  resources :searchterms do
    collection do
      get :warm, :action =>'warm', :as => 'warm'
    end
  end

require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
include ProductsHelper

  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

def search_post
  redirect_to search_products_path(params[:query])
end



  # GET /products/1/edit
  def search

	 @searchterm = "#{params[:query]}"
     @pb = ProgressBar.create(message: 'Queued',percent:0)

     @products = GetProducts(@searchterm)
      respond_to do |format|
        format.html # seek.html.haml
      end
    
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:sem3_id, :name, :sitedetails, :brand, :cat_id, :category, :color, :created_at, :description, :ean, :features, :gtins, :geo, :height, :images, :images_total, :length, :manufacturer, :model, :mpn, :price, :price_currency, :size, :upc, :updated_at, :variation_id, :variation_secondaryids, :weight, :width)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  require 'semantics3'

  # Your Semantics3 API Credentials

  API_KEY = 'SEM31A43B565A507E41AA6200E14BCBEC051'
  API_SECRET = 'MjU3NDgxMjE0MjI1YzMwYzcyNTVhM2VkZjFmMzM3YzY'

  def GetProducts(searchterm)
    #make this a helpe
    searchterm = "#{searchterm}"
    ap searchterm

    @products = Rails.cache.fetch(searchterm, expires_in: 12.hours) do
      # Set up a client to talk to the Semantics3 API
      sem3 = Semantics3::Products.new(API_KEY,API_SECRET)
      #          # Build the request
      sem3.products_field( "fields",["sitedetails", "name", "price", "brand"])
      sem3.products_field( "activeproductsonly", 1)
      sem3.products_field( "search", searchterm)

      #      # Run the request
      productsHash = sem3.get_products()
      ap productsHash

      #      # View the results of the reques
      #      # Run the request
      productsHash = sem3.iterate_products
      #      # View the results of the request
      # todo
      #this is wonky and could use some sprucing.
      @products_json = productsHash.to_json
      ap @products_json
      @products = [] if @products_json == "null"
      unless @products_json == "null"
        @productsy = JSON.parse(@products_json)
        @products = @productsy["results"]
        Rails.cache.write(searchterm,@products)  
      end
      
      @products
      #Product.create(@products)
    end
  end
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :sem3_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sem3_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sem3_id) %>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :sitedetails, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sitedetails, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sitedetails) %>
  </div>
  <div class="form-group">
    <%= f.label :brand, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :brand, :class => 'form-control' %>
    </div>
    <%=f.error_span(:brand) %>
  </div>
  <div class="form-group">
    <%= f.label :cat_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cat_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cat_id) %>
  </div>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :category, :class => 'form-control' %>
    </div>
    <%=f.error_span(:category) %>
  </div>
  <div class="form-group">
    <%= f.label :color, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :color, :class => 'form-control' %>
    </div>
    <%=f.error_span(:color) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :ean, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :ean, :class => 'form-control' %>
    </div>
    <%=f.error_span(:ean) %>
  </div>
  <div class="form-group">
    <%= f.label :features, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :features, :class => 'form-control' %>
    </div>
    <%=f.error_span(:features) %>
  </div>
  <div class="form-group">
    <%= f.label :gtins, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gtins, :class => 'form-control' %>
    </div>
    <%=f.error_span(:gtins) %>
  </div>
  <div class="form-group">
    <%= f.label :geo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :geo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:geo) %>
  </div>
  <div class="form-group">
    <%= f.label :height, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :height, :class => 'form-control' %>
    </div>
    <%=f.error_span(:height) %>
  </div>
  <div class="form-group">
    <%= f.label :images, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :images, :class => 'form-control' %>
    </div>
    <%=f.error_span(:images) %>
  </div>
  <div class="form-group">
    <%= f.label :images_total, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :images_total, :class => 'form-control' %>
    </div>
    <%=f.error_span(:images_total) %>
  </div>
  <div class="form-group">
    <%= f.label :length, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :length, :class => 'form-control' %>
    </div>
    <%=f.error_span(:length) %>
  </div>
  <div class="form-group">
    <%= f.label :manufacturer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :manufacturer, :class => 'form-control' %>
    </div>
    <%=f.error_span(:manufacturer) %>
  </div>
  <div class="form-group">
    <%= f.label :model, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :model, :class => 'form-control' %>
    </div>
    <%=f.error_span(:model) %>
  </div>
  <div class="form-group">
    <%= f.label :mpn, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mpn, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mpn) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :price_currency, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price_currency, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price_currency) %>
  </div>
  <div class="form-group">
    <%= f.label :size, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :size, :class => 'form-control' %>
    </div>
    <%=f.error_span(:size) %>
  </div>
  <div class="form-group">
    <%= f.label :upc, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :upc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:upc) %>
  </div>
  <div class="form-group">
    <%= f.label :variation_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :variation_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:variation_id) %>
  </div>
  <div class="form-group">
    <%= f.label :variation_secondaryids, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :variation_secondaryids, :class => 'form-control' %>
    </div>
    <%=f.error_span(:variation_secondaryids) %>
  </div>
  <div class="form-group">
    <%= f.label :weight, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :weight, :class => 'form-control' %>
    </div>
    <%=f.error_span(:weight) %>
  </div>
  <div class="form-group">
    <%= f.label :width, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :width, :class => 'form-control' %>
    </div>
    <%=f.error_span(:width) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:sem3_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:sitedetails) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:cat_id) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:color) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:ean) %></th>
      <th><%= model_class.human_attribute_name(:features) %></th>
      <th><%= model_class.human_attribute_name(:gtins) %></th>
      <th><%= model_class.human_attribute_name(:geo) %></th>
      <th><%= model_class.human_attribute_name(:height) %></th>
      <th><%= model_class.human_attribute_name(:images) %></th>
      <th><%= model_class.human_attribute_name(:images_total) %></th>
      <th><%= model_class.human_attribute_name(:length) %></th>
      <th><%= model_class.human_attribute_name(:manufacturer) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:mpn) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:price_currency) %></th>
      <th><%= model_class.human_attribute_name(:size) %></th>
      <th><%= model_class.human_attribute_name(:upc) %></th>
      <th><%= model_class.human_attribute_name(:variation_id) %></th>
      <th><%= model_class.human_attribute_name(:variation_secondaryids) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:width) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.sem3_id %></td>
        <td><%= product.name %></td>
        <td><%= product.sitedetails %></td>
        <td><%= product.brand %></td>
        <td><%= product.cat_id %></td>
        <td><%= product.category %></td>
        <td><%= product.color %></td>
        <td><%= product.description %></td>
        <td><%= product.ean %></td>
        <td><%= product.features %></td>
        <td><%= product.gtins %></td>
        <td><%= product.geo %></td>
        <td><%= product.height %></td>
        <td><%= product.images %></td>
        <td><%= product.images_total %></td>
        <td><%= product.length %></td>
        <td><%= product.manufacturer %></td>
        <td><%= product.model %></td>
        <td><%= product.mpn %></td>
        <td><%= product.price %></td>
        <td><%= product.price_currency %></td>
        <td><%= product.size %></td>
        <td><%= product.upc %></td>
        <td><%= product.variation_id %></td>
        <td><%= product.variation_secondaryids %></td>
        <td><%= product.weight %></td>
        <td><%= product.width %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/search.html.haml
- if !@products.nil? && !@products.empty?
	- @products.each do |product|
		.card.hoverable
			.card-content.blue.lighten-5

				- if product["sitedetails"][0]
					%h5.h5-responsive
						= link_to(product["name"].gsub(/\[.*\]/,''),product["sitedetails"][0]["url"])
				- else
					%h5.thin-200
						= product["name"]
			.card-content
				%h6.h6-responsive.section-title.st-blue
					= link_to("$#{product['price']}",product["sitedetails"][0]["url"],:class=>"btn btn-default btn-md waves-effect waves-light")
					%small.card-btn
						By #{product["brand"]}

				%h6.h6-responsive
				- if product["sitedetails"][0]
					= link_to("Sold by #{product['sitedetails'][0]['name']}",product["sitedetails"][0]["url"])
- else 
	%h5.h5-responsive
		Looks like there aren't any #{params[:query]}s here! (0 results for #{params[:query]})

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:sem3_id) %>:</strong></dt>
  <dd><%= @product.sem3_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sitedetails) %>:</strong></dt>
  <dd><%= @product.sitedetails %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brand) %>:</strong></dt>
  <dd><%= @product.brand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cat_id) %>:</strong></dt>
  <dd><%= @product.cat_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @product.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:color) %>:</strong></dt>
  <dd><%= @product.color %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ean) %>:</strong></dt>
  <dd><%= @product.ean %></dd>
  <dt><strong><%= model_class.human_attribute_name(:features) %>:</strong></dt>
  <dd><%= @product.features %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gtins) %>:</strong></dt>
  <dd><%= @product.gtins %></dd>
  <dt><strong><%= model_class.human_attribute_name(:geo) %>:</strong></dt>
  <dd><%= @product.geo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:height) %>:</strong></dt>
  <dd><%= @product.height %></dd>
  <dt><strong><%= model_class.human_attribute_name(:images) %>:</strong></dt>
  <dd><%= @product.images %></dd>
  <dt><strong><%= model_class.human_attribute_name(:images_total) %>:</strong></dt>
  <dd><%= @product.images_total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:length) %>:</strong></dt>
  <dd><%= @product.length %></dd>
  <dt><strong><%= model_class.human_attribute_name(:manufacturer) %>:</strong></dt>
  <dd><%= @product.manufacturer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @product.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mpn) %>:</strong></dt>
  <dd><%= @product.mpn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price_currency) %>:</strong></dt>
  <dd><%= @product.price_currency %></dd>
  <dt><strong><%= model_class.human_attribute_name(:size) %>:</strong></dt>
  <dd><%= @product.size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:upc) %>:</strong></dt>
  <dd><%= @product.upc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:variation_id) %>:</strong></dt>
  <dd><%= @product.variation_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:variation_secondaryids) %>:</strong></dt>
  <dd><%= @product.variation_secondaryids %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @product.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:width) %>:</strong></dt>
  <dd><%= @product.width %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>